// <auto-generated />
using System;
using Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data__Lớp_dữ_liệu_.Migrations
{
    [DbContext(typeof(QuanLyKhoContext))]
    partial class QuanLyKhoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Core.Entities.CT_HoaDon", b =>
                {
                    b.Property<string>("MaHD")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnOrder(0);

                    b.Property<string>("MaSerial")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(1);

                    b.Property<decimal?>("GiaBanThucTe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MaSP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaHD", "MaSerial");

                    b.HasIndex("MaSerial");

                    b.ToTable("CT_Hoa_Don");
                });

            modelBuilder.Entity("Core.Entities.CT_PhieuNhap", b =>
                {
                    b.Property<string>("MaPN")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnOrder(0);

                    b.Property<string>("MaSP")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(1);

                    b.Property<decimal?>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.Property<decimal?>("ThanhTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaPN", "MaSP");

                    b.HasIndex("MaSP");

                    b.ToTable("CT_Phieu_Nhap");
                });

            modelBuilder.Entity("Core.Entities.CauHinhHeThong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MauChuDao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MauNen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MauNhan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NganHang")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SoTaiKhoan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenChuTaiKhoan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenCuaHang")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CauHinhHeThong");
                });

            modelBuilder.Entity("Core.Entities.ChiNhanh", b =>
                {
                    b.Property<string>("MaCN")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TenCN")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaCN");

                    b.ToTable("Chi_Nhanh");
                });

            modelBuilder.Entity("Core.Entities.ChucNang", b =>
                {
                    b.Property<string>("MaChucNang")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NhomChucNang")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenChucNang")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaChucNang");

                    b.ToTable("Chuc_Nang");
                });

            modelBuilder.Entity("Core.Entities.DanhMuc", b =>
                {
                    b.Property<string>("MaDM")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TenDM")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaDM");

                    b.ToTable("Danh_Muc");
                });

            modelBuilder.Entity("Core.Entities.HoaDon", b =>
                {
                    b.Property<string>("MaHD")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MaCN")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaKH")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaND")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("NgayLap")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhuongThucTT")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("TienGiam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TongThanhToan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TongTienHang")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaHD");

                    b.HasIndex("MaKH");

                    b.HasIndex("MaND");

                    b.ToTable("Hoa_Don");
                });

            modelBuilder.Entity("Core.Entities.KhachHang", b =>
                {
                    b.Property<string>("MaKH")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("DiemTichLuy")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TenKH")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaKH");

                    b.ToTable("Khach_Hang");
                });

            modelBuilder.Entity("Core.Entities.LichSuHeThong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("HanhDong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiThucHien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("LichSuHeThong");
                });

            modelBuilder.Entity("Core.Entities.NguoiDung", b =>
                {
                    b.Property<string>("MaND")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaCN")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaNhomQuyen")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<string>("VaiTro")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaND");

                    b.HasIndex("MaCN");

                    b.HasIndex("MaNhomQuyen");

                    b.ToTable("Nguoi_Dung");
                });

            modelBuilder.Entity("Core.Entities.NhomQuyen", b =>
                {
                    b.Property<string>("MaNhomQuyen")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenNhomQuyen")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaNhomQuyen");

                    b.ToTable("Nhom_Quyen");
                });

            modelBuilder.Entity("Core.Entities.PhanQuyen", b =>
                {
                    b.Property<string>("MaNhomQuyen")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnOrder(0);

                    b.Property<string>("MaChucNang")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(1);

                    b.Property<bool?>("DuocPhep")
                        .HasColumnType("bit");

                    b.HasKey("MaNhomQuyen", "MaChucNang");

                    b.HasIndex("MaChucNang");

                    b.ToTable("Phan_Quyen");
                });

            modelBuilder.Entity("Core.Entities.PhieuBaoHanh", b =>
                {
                    b.Property<string>("MaPBH")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LoiGhiNhan")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MaND")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaSerial")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("NgayNhan")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTraDuKien")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaPBH");

                    b.HasIndex("MaND");

                    b.HasIndex("MaSerial");

                    b.ToTable("Phieu_Bao_Hanh");
                });

            modelBuilder.Entity("Core.Entities.PhieuNhap", b =>
                {
                    b.Property<string>("MaPN")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MaCN")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaNCC")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaND")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("NgayNhap")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaPN");

                    b.HasIndex("MaCN");

                    b.HasIndex("MaNCC");

                    b.HasIndex("MaND");

                    b.ToTable("Phieu_Nhap");
                });

            modelBuilder.Entity("Core.Entities.SanPham", b =>
                {
                    b.Property<string>("MaSP")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal?>("DonGiaNhap")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DonViTinh")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("GiaBan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("GiaNhap")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaDM")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaVach")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SoLuongTon")
                        .HasColumnType("int");

                    b.Property<string>("TenSP")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ThoiGianBaoHanh")
                        .HasColumnType("int");

                    b.Property<string>("ThongSoChiTiet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaSP");

                    b.HasIndex("MaDM");

                    b.ToTable("San_Pham");
                });

            modelBuilder.Entity("Core.Entities.SerialSP", b =>
                {
                    b.Property<string>("MaSerial")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaCN")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaSP")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("SoSerial")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaSerial");

                    b.HasIndex("MaCN");

                    b.HasIndex("MaSP");

                    b.ToTable("SerialSP");
                });

            modelBuilder.Entity("Core.Entities.ThongTinCongTy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("ChoPhepBanHang")
                        .HasColumnType("bit");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaSoThue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenCongTy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ThongTinCongTy");
                });

            modelBuilder.Entity("NhaCungCap", b =>
                {
                    b.Property<string>("MaNCC")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal?>("CongNoPhaiTra")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SDT")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TenNCC")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaNCC");

                    b.ToTable("Nha_Cung_Cap");
                });

            modelBuilder.Entity("Core.Entities.CT_HoaDon", b =>
                {
                    b.HasOne("Core.Entities.HoaDon", "HoaDon")
                        .WithMany("CT_HoaDons")
                        .HasForeignKey("MaHD")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Core.Entities.SerialSP", "SerialSP")
                        .WithMany()
                        .HasForeignKey("MaSerial")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HoaDon");

                    b.Navigation("SerialSP");
                });

            modelBuilder.Entity("Core.Entities.CT_PhieuNhap", b =>
                {
                    b.HasOne("Core.Entities.PhieuNhap", "PhieuNhap")
                        .WithMany("CT_PhieuNhaps")
                        .HasForeignKey("MaPN")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Core.Entities.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("MaSP")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PhieuNhap");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("Core.Entities.HoaDon", b =>
                {
                    b.HasOne("Core.Entities.KhachHang", "KhachHang")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaKH")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Core.Entities.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("MaND")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("Core.Entities.NguoiDung", b =>
                {
                    b.HasOne("Core.Entities.ChiNhanh", "ChiNhanh")
                        .WithMany()
                        .HasForeignKey("MaCN")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Core.Entities.NhomQuyen", "NhomQuyen")
                        .WithMany("NguoiDungs")
                        .HasForeignKey("MaNhomQuyen")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ChiNhanh");

                    b.Navigation("NhomQuyen");
                });

            modelBuilder.Entity("Core.Entities.PhanQuyen", b =>
                {
                    b.HasOne("Core.Entities.ChucNang", "ChucNang")
                        .WithMany("PhanQuyens")
                        .HasForeignKey("MaChucNang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Core.Entities.NhomQuyen", "NhomQuyen")
                        .WithMany("PhanQuyens")
                        .HasForeignKey("MaNhomQuyen")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChucNang");

                    b.Navigation("NhomQuyen");
                });

            modelBuilder.Entity("Core.Entities.PhieuBaoHanh", b =>
                {
                    b.HasOne("Core.Entities.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("MaND")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Core.Entities.SerialSP", "SerialSP")
                        .WithMany()
                        .HasForeignKey("MaSerial")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NguoiDung");

                    b.Navigation("SerialSP");
                });

            modelBuilder.Entity("Core.Entities.PhieuNhap", b =>
                {
                    b.HasOne("Core.Entities.ChiNhanh", "ChiNhanh")
                        .WithMany()
                        .HasForeignKey("MaCN")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NhaCungCap", "NhaCungCap")
                        .WithMany()
                        .HasForeignKey("MaNCC")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Core.Entities.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("MaND")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChiNhanh");

                    b.Navigation("NguoiDung");

                    b.Navigation("NhaCungCap");
                });

            modelBuilder.Entity("Core.Entities.SanPham", b =>
                {
                    b.HasOne("Core.Entities.DanhMuc", "DanhMuc")
                        .WithMany("SanPhams")
                        .HasForeignKey("MaDM")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DanhMuc");
                });

            modelBuilder.Entity("Core.Entities.SerialSP", b =>
                {
                    b.HasOne("Core.Entities.ChiNhanh", "ChiNhanh")
                        .WithMany()
                        .HasForeignKey("MaCN")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Core.Entities.SanPham", "SanPham")
                        .WithMany("SerialSPs")
                        .HasForeignKey("MaSP")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChiNhanh");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("Core.Entities.ChucNang", b =>
                {
                    b.Navigation("PhanQuyens");
                });

            modelBuilder.Entity("Core.Entities.DanhMuc", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("Core.Entities.HoaDon", b =>
                {
                    b.Navigation("CT_HoaDons");
                });

            modelBuilder.Entity("Core.Entities.KhachHang", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("Core.Entities.NhomQuyen", b =>
                {
                    b.Navigation("NguoiDungs");

                    b.Navigation("PhanQuyens");
                });

            modelBuilder.Entity("Core.Entities.PhieuNhap", b =>
                {
                    b.Navigation("CT_PhieuNhaps");
                });

            modelBuilder.Entity("Core.Entities.SanPham", b =>
                {
                    b.Navigation("SerialSPs");
                });
#pragma warning restore 612, 618
        }
    }
}
